title: Ann 's blog 
author: Vy Ngoc Anh Hua
email: vyngocanh-hua@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It Is Never To Late To Learn.
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  vyngocanh-hua # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
